### PR TITLE
Remove apparently obsolete setup.cfg

### PR DESCRIPTION
**Pull request by bittner**
The `setup.cfg` file contains configuration data that used to be read by tools like Tox and Sphinx.

The respective values now appear in [pyproject.toml](https://github.com/jazzband/django-analytical/blob/main/pyproject.toml#L11-L20) and [tox.ini](https://github.com/jazzband/django-analytical/blob/main/tox.ini#L44-L47), and it looks like the entire file is hence obsolete.

I'm not 100% sure whether ReadTheDocs reads the file, but I guess building the docs should work just fine without it.

### CODE REVIEW

**Comment by bittner** [comment]
Please, anyone, review this PR, so we can merge it!

@jezdez @smithdc1 @PiDelport @jcassee

**Review by jezdez — APPROVED** [review]

**Comment by bittner** [comment]
Thanks Jannis!

**Comment by jezdez** [comment]
@bittner NP, did you see that the CI system isn't working correctly?

**Comment by bittner** [comment]
> @bittner NP, did you see that the CI system isn't working correctly?

Do you intend what I just described in https://github.com/jazzband/django-analytical/pull/226#pullrequestreview-1408576409?

**Pull request merged**
