### PR TITLE
Make sure new Google Analytics anonimyze IP calls also happen before sending pageviews

### PR DESCRIPTION
**Pull request by vdboor**
In #127 I made sure that the old `ga.js` analytics code used the proper ordering of calls. It seems that the new `analytics.js` code introduced by #135 has the same issue.

Currently it renders:

```
ga('create', 'UA-25383750-9', 'auto', {});
 
ga('send', 'pageview');
ga('set', 'anonymizeIp', true);
```

The send method should happen as last method call however.

I checked the contents of the `{commands}` placeholder, and it can only consist of `ga('set', ...)` commands.

### CODE REVIEW

**Comment by bittner** [comment]
The Bandit check [is allowed to fail](https://github.com/jazzband/django-analytical/blob/master/.travis.yml#L18-L19), currently. I've opened an issue to have us reminded about fixing it.

**Comment by vdboor** [comment]
@jcassee thanks for the quick response!
I've fixed the tests errors. It turned out that the script output included an extra blank line now. I've updated the `commands` construction so it always outputs one command per line, and all tests pass.

**Comment by jcassee** [comment]
@bittner GitHub added an "Update branch" button to merge master into the feature branch. Do you have objections to using that instead of asking for a rebase?

**Comment by bittner** [comment]
I don't really know. It's certainly a convenience feature. If GitHub is doing a merge commit, as the description says, there's little to nothing that can go wrong. I wouldn't be worried.

**Comment by vdboor** [comment]
Thanks! :-D

**Pull request merged**
