### PR TITLE
Replace deprecated readme check

### PR DESCRIPTION
**Pull request by bittner**
These changes fix the failing build jobs in PR #146.

@jcassee Do you want to push the Flake8 fixes to this PR? :smirk: 

**P.S.:** Greetings from Paris CDG airport! :wave:

### CODE REVIEW

**Comment by bittner** [comment]
Travis CI is so broken: The [sqlite3 version is too old](https://travis-ci.org/jazzband/django-analytical/jobs/517318668#L521) (for Django), and this is Python 3.6.3's fault. A current 3.6.7 Python ships sqlite3 3.22.0. It's a pain.

The flake8 complaints are actually caused by the [pseudo-type hinting](https://github.com/jazzband/django-analytical/blob/master/analytical/templatetags/intercom.py#L32) with the comments. Since when does Flake8 deal with that? Interesting.

**Comment by jcassee** [comment]
@bittner did you see #147? :smile:

**Comment by bittner** [comment]
Cool! Python 2.7 fixes Travis CI's sqlite version issue. :unamused:

**Comment by bittner** [comment]
Thanks, Joost! Talk to you in an hour. The plane is about to take off. :airplane:

**Comment by bittner** [comment]
Closing this in favor of PR #147. :+1:

**Pull request closed without merging**
